# Uncomment the next line to define a global platform for your project
target 'SITAMPC_Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SITAMPC_Example

 pod 'SITAMPC', :path => '../'

  target 'SITAMPC_Tests' do
    inherit! :search_paths

    
  end


end


 
